### PR TITLE
feat: EIP1559 checks

### PR DESCRIPTION
**Pull request by TAdev0**
## Pull Request type

 EIP1559 checks in `__validate__` function

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #742

- - -
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778)

### CODE REVIEW

**Comment by TAdev0** [comment]
@enitrat  checks should be good
i'm debugging the 3 tests failing with entrypoint errors

**Comment by TAdev0** [comment]
@enitrat  ready for review

**Review by enitrat — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @ClementWalter and @TAdev0)

___
*[`crates/contracts/src/account_contract.cairo` line 86 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlSNQmDLbiiDQs1RyQ:-NvlSNQmDLbiiDQs1RyR:brsq57n) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L86)):*
> ```Cairo
>         Account_implementation: ClassHash,
>         Account_evm_address: EthAddress,
>         Kakarot_address: ContractAddress,
> ```

redundant with ownable.owner
___
*[`crates/contracts/src/account_contract.cairo` line 191 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlSvOp50LS_hQWaaq3:-NvlSvOp50LS_hQWaaq4:b-tcyhm5) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L191)):*
> ```Cairo
>             match tx.try_into_fee_market_transaction() {
>                 Option::Some(tx_fee_infos) => {
>                     let kakarot = IKakarotCoreDispatcher {
> ```

this entire body should be extracted to its own function
___
*[`crates/contracts/src/account_contract.cairo` line 196 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlT6yCE3NZmwePDmc6:-NvlT6yCE3NZmwePDmc7:bdsr0gs) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L196)):*
> ```Cairo
>                     let block_gas_limit = kakarot.get_block_gas_limit();
>                     let tx_gas_limit = tx.gas_limit();
>                     assert(tx_gas_limit < block_gas_limit, 'tx gas does not fit in block');
> ```

you can inline it



_Suggestion:_
```Cairo
tx.gas_limit()
```
___
*[`crates/contracts/src/account_contract.cairo` line 196 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlTL8vADE1uuL8Lydd:-NvlTL8vADE1uuL8Lyde:bls9t1a) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L196)):*
> ```Cairo
>                     let block_gas_limit = kakarot.get_block_gas_limit();
>                     let tx_gas_limit = tx.gas_limit();
>                     assert(tx_gas_limit < block_gas_limit, 'tx gas does not fit in block');
> ```

you will not want to assert and panic but just early return an unsuccessful execution
___
*[`crates/contracts/src/account_contract.cairo` line 201 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlSf6v9fSccIVbuPaE:-NvlSf6v9fSccIVbuPaF:bc6ue9n) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L201)):*
> ```Cairo
>                     let native_token = kakarot.get_native_token();
>                     let balance = ERC20ABIDispatcher { contract_address: native_token }
>                         .balance_of(get_contract_address());
> ```

this will not work, you cannot make external calls in __validate__. This needs to be under the __execute__ flow

https://github.com/kkrt-labs/kakarot-ssj/blob/78c2281cd49dfa216cab3008910f057d8ae661f6/crates/contracts/src/account_contract.cairo#L213
___
*[`crates/contracts/src/account_contract.cairo` line 207 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlTXze03-dTkg563HT:-NvlTXze03-dTkg563HU:bb7od0r) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L207)):*
> ```Cairo
> 
>                     // ensure that the user was willing to at least pay the base fee
>                     assert(base_fee < max_fee_per_gas, 'max fee per gas is too low');
> ```

same
___
*[`crates/contracts/src/account_contract.cairo` line 213 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlTf_G7IRjXjfvSOaN:-NvlTf_G7IRjXjfvSOaO:bb7od0r) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L213)):*
> ```Cairo
>                     let max_gas_fee = tx_gas_limit * max_fee_per_gas;
>                     let tx_cost = max_gas_fee.into() + tx_fee_infos.amount;
>                     assert(tx_cost < balance, 'balance cannot cover tx cost');
> ```

same

**Review by TAdev0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/contracts/src/account_contract.cairo` line 86 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlSNQmDLbiiDQs1RyQ:-Nvl_eZo4wmRGyOl8hth:btfneha) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L86)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

redundant with ownable.owner
</blockquote></details>

true. thanks
___
*[`crates/contracts/src/account_contract.cairo` line 191 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlSvOp50LS_hQWaaq3:-Nvl_mObCaLWNlrhX-fS:b-ffreo5) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L191)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

this entire body should be extracted to its own function
</blockquote></details>

what do you mean?
___
*[`crates/contracts/src/account_contract.cairo` line 196 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlT6yCE3NZmwePDmc6:-Nvl_umIEOt9suP_BpFB:bc06spm) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L196)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

you can inline it
</blockquote></details>

ok . I did that because we use it twice. I change back
___
*[`crates/contracts/src/account_contract.cairo` line 196 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlTL8vADE1uuL8Lydd:-Nvlak_FAfheRHG9wm8r:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L196)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

you will not want to assert and panic but just early return an unsuccessful execution
</blockquote></details>

done
___
*[`crates/contracts/src/account_contract.cairo` line 201 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlSf6v9fSccIVbuPaE:-NvlalrQ82CYhHo4GZvj:b-s408kr) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L201)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

this will not work, you cannot make external calls in __validate__. This needs to be under the __execute__ flow

https://github.com/kkrt-labs/kakarot-ssj/blob/78c2281cd49dfa216cab3008910f057d8ae661f6/crates/contracts/src/account_contract.cairo#L213
</blockquote></details>

oh yeah i didn't know that. thanks
___
*[`crates/contracts/src/account_contract.cairo` line 207 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlTXze03-dTkg563HT:-Nvlb3vj9chAimIhYGlq:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L207)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`crates/contracts/src/account_contract.cairo` line 213 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778#-NvlTf_G7IRjXjfvSOaN:-Nvlb3Yl2RsUeaZqmnky:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f61bb59e0c53ec2ebf33e874f48d47c83d8a4918/crates/contracts/src/account_contract.cairo#L213)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by enitrat — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ClementWalter)

**Pull request merged**
