### PR TITLE
feat(gas): finalize contract creation & handle revert opcode executio…

### LINKED ISSUE #620: feat(gas): charge gas on created contract code
## Feature Request
When creating a contract, we should charge len(contract) * CODEDEPOSIT gas.

### LINKED ISSUE #621: feat(gas): a reverting context must consume all of its gas
## Feature Request

When a context reverts under an exceptional halt, we must consume all of its gas.

in `process_create_message`, we will ensure that any failure when setting the code of the account will __REVERT__ the state and consume the whole gas.

in `execute_code`, we will consume the entire remaining gas if the EVM __exceptionally__ reverts (that is, not because of the REVERT opcode)

### PR DESCRIPTION
**Pull request by enitrat**
…n result

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #632 Resolves #621 Resolves #620

## What is the new behavior?

- Handle create contract finalization gas costs and invariants
- Correctly handle returned `ExecutionResult` incase of __exceptional__ revert
- Correctly handle returned `Executionresult` in case of __normal__ revert (opcode REVERT)

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637)

### CODE REVIEW

**Review by bajpai244 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/evm/src/model.cairo` line 57 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637#-Nl9NVpa7gqHg6a0iF_1:-Nl9NVpa7gqHg6a0iF_2:b3wleg9) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/67939efda87ee245a8467399c96fd59121949b87/crates/evm/src/model.cairo#L57)):*
> ```Cairo
> #[generate_trait]
> impl ExecutionResultImpl of ExecutionResultTrait {
>     fn exceptional_failure(error: Span<u8>) -> ExecutionResult {
> ```

I guess we should also take `accessed_addresses` & `acessed_storage_ keys` as inputs as well right? Because when I look at the previous implementation, it looks like we were using `vm.accessed_addresses()` & `vm.accessed_storage_ keys()` for them?


___
*[`crates/evm/src/model/vm.cairo` line 48 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637#-Nl9MeIB7CyCwI3DtGhm:-Nl9MeIB7CyCwI3DtGhn:b-73m6vw) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/67939efda87ee245a8467399c96fd59121949b87/crates/evm/src/model/vm.cairo#L48)):*
> ```Cairo
>     }
> 
>     /// Decrements the gas_left field of the current vm by the value amount.
> ```

Nice catch!

**Review by enitrat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/evm/src/model.cairo` line 57 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637#-Nl9NVpa7gqHg6a0iF_1:-Nl9PLa_9ntxwcj0h8_4:b-jsdfiw) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/67939efda87ee245a8467399c96fd59121949b87/crates/evm/src/model.cairo#L57)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

I guess we should also take `accessed_addresses` & `acessed_storage_ keys` as inputs as well right? Because when I look at the previous implementation, it looks like we were using `vm.accessed_addresses()` & `vm.accessed_storage_ keys()` for them?
</blockquote></details>

At first I thought that on exceptional failure, the accessed addresses would be discarded, but indeed as they're not par of the state, it seems that they're kept warm. 

Done.
___
*[`crates/evm/src/model/vm.cairo` line 48 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637#-Nl9MeIB7CyCwI3DtGhm:-Nl9RvsT3HdWVfMUeIZh:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/67939efda87ee245a8467399c96fd59121949b87/crates/evm/src/model/vm.cairo#L48)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Nice catch!
</blockquote></details>

Done.

**Review by bajpai244 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/evm/src/create_helpers.cairo` line 164 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637#-Nl9Vc8A2njvx8G3KQV1:-Nl9Vc8A2njvx8G3KQV2:b484i4f) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/67939efda87ee245a8467399c96fd59121949b87/crates/evm/src/create_helpers.cairo#L164)):*
> ```Cairo
> 
>         if code.len() != 0 {
>             ensure(*code[0] != 0xEF, EVMError::InvalidCode)?;
> ```

I guess we should put in comment some reference to https://eips.ethereum.org/EIPS/eip-3541.
___
*[`crates/evm/src/interpreter.cairo` line 125 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637#-Nl9PYrODvgKVHIpdw12:-Nl9PYrODvgKVHIpdw13:b-yomekc) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/67939efda87ee245a8467399c96fd59121949b87/crates/evm/src/interpreter.cairo#L125)):*
> ```Cairo
>         }
> 
>         // Instantiate a new VM using the message to process and the current environment.
> ```

nice catch!

**Review by bajpai244 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/evm/src/create_helpers.cairo` line 164 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637#-Nl9Vc8A2njvx8G3KQV1:-NlBzvaa67fGrVCet6PK:b-uf2g91) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/67939efda87ee245a8467399c96fd59121949b87/crates/evm/src/create_helpers.cairo#L164)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Not sure, I would rather keep the codebase clean from too many comments especialy given that we have EELS for specs
</blockquote></details>

Cool, I guess fine for me then, but I prefer to add docs for subtle things, saves time for someone reading the code!

**Review by bajpai244 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/637#-:-NlC1u-C3egVr_D5SN11:bnfp4nl)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ClementWalter and @enitrat)

**Pull request merged**
