### PR TITLE
refactor: simplify returns

### PR DESCRIPTION
**Pull request by lambda-0x**
## Pull Request type

Please check the type of change your PR introduces:

- [x] Refactoring (no functional changes, no API changes)

## What is the current behavior?

Resolves: #190 

## What is the new behavior?

- simplifies the returns

## Does this introduce a breaking change?

- [x] No

### CODE REVIEW

**Comment by enitrat** [comment]
Can you also do the same for the `decode_and_execute` function?

**Comment by lambda-0x** [comment]
image

need to use `return` instead of `?;` , is that fine?

**Comment by enitrat** [comment]
> need to use return instead of ?; , is that fine?

yep, this is intended, this is because you want to propagate the error to the calling function

**Comment by enitrat** [comment]
> also there is a bug in that function, we should be never reaching this (Unknown opcode) part of code because u8 max value is 255 and we are covering all possible values in if branches.

there are less than 255 opcodes actually, so you could end up trying to hit an unexisting value, which would result in calling an unknown opcode. Even if max_u8 is 255

**Comment by lambda-0x** [comment]
(made suggested changes and rebased branch to latest main)

**Comment by lambda-0x** [comment]
(CI failure unrelated to PR, might be related to: https://github.com/kkrt-labs/kakarot-ssj/pull/217)

**Comment by enitrat** [comment]
> (CI failure unrelated to PR, might be related to: https://github.com/kkrt-labs/kakarot-ssj/pull/217)

yes, I think the action doesn't have the required permissions, but if tests pass it's ok

**Review by enitrat — APPROVED** [review]
lgtm

**Pull request merged**
