### PR TITLE
dev: Remove deploy fee

### PR DESCRIPTION
**Pull request by TAdev0**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Resolves: #729 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/732)

### CODE REVIEW

**Review by enitrat — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/732)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ClementWalter)

**Comment by Eikix** [comment]
@greged93 wdyt? we're removing deploy_fee from SSJ altogether, but it might break ef-tests

**Comment by greged93** [comment]
Let me check quickly, not sure it will break anything but still would be nicer to remove on ef-tests first.

**Comment by greged93** [comment]
Made a PR here: https://github.com/kkrt-labs/ef-tests/pull/654
but I think it's fine to merge this, should not have any impact.

**Pull request merged**
