### PR TITLE
feat: use scarb macro to generate const powers

### PR DESCRIPTION
**Pull request by juankohler**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #841

## What is the new behavior?

- Uses pow! macro instead of hardcoded constants.
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/865)

### CODE REVIEW

**Comment by juankohler** [comment]
hi @enitrat 
I am importing the alexandria_macros package in crates/utils/Scarb.toml, but when I try to use it in utils/src/helpers.cairo, it gives me an 'Identifier not found.' error on the line 'use alexandria_macros::pow'. Can you help me with this please?

**Comment by juankohler** [comment]
Hi @enitrat, I have a problem. When I took the issue, I interpreted that I needed to export the Alexandria package, but then I realized that it was in Rust. When I looked into how to calculate the power of 2 at compile time in Cairo, I couldn't find any solution. The current utils only calculate at runtime up to 128. The only way I can think of is to hardcode the constants up to that number and create a function that returns them depending on the argument passed, but this doesn't seem like an optimal solution. Could you help me with this?

**Comment by enitrat** [comment]
I don't understand the problem. Can't you use the macro?

**Comment by enitrat** [comment]
merge blocked until snfoundry allows use of scarb macros

**Pull request closed without merging**
