### PR TITLE
feat: add sha256 precompile

### PR DESCRIPTION
**Pull request by bajpai244**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- SHA-256 precompile isn't implemented

Resolves: #676 

## What is the new behavior?

This pr adds support for SHA-256 precompile.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677)

### CODE REVIEW

**Review by Eikix — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677)* status: 4 of 13 files reviewed, 6 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/alexandria_math/src/sha256.cairo` line 1 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5hxcpEIqdN53IRYW7:-Nm5hxcpEIqdN53IRYW8:b-552ety) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/alexandria_math/src/sha256.cairo#L1)):*
> ```Cairo
> use integer::{u32_wrapping_add, BoundedInt};
> ```

Lets add a comment at the top explaining that we copy pasted this alexandria code as a temporary solution to enable us to change scarb versions as we see fit, and add a link to alexandria 
___
*[`crates/alexandria_math/src/sha256.cairo` line 72 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5ic2K8OGrvNjAct0E:-Nm5ic2K8OGrvNjAct0F:b62char) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/alexandria_math/src/sha256.cairo#L72)):*
> ```Cairo
>     data.append(res.try_into().unwrap());
>     res = (data_len.into() & 0xff0000) / 0x10000;
>     data.append(res.try_into().unwrap());
> ```

i see a lot of unwraps in their implementation, are they all safe unwraps?

i guess we'll see with some ef-tests if we get some panics,

but it'd be good to do some amount of sanity check that this code cannot panic, because we must not panic in the precompile
___
*[`crates/alexandria_math/src/sha256.cairo` line 277 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5iB-P2j0EaFhxcJkO:-Nm5iB-P2j0EaFhxcJkP:bz9c405) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/alexandria_math/src/sha256.cairo#L277)):*
> ```Cairo
>         0xc67178f2
>     ]
> }
> ```

open question: should we add their tests as well? for soundness
this also applies to other packages we copy pasted i guess
___
*[`crates/evm/src/precompiles/lib.cairo` line 27 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5iJV6CiAbMHpM1h80:-Nm5iJV6CiAbMHpM1h81:b9btd7g) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/evm/src/precompiles/lib.cairo#L27)):*
> ```Cairo
>             },
>             2 => {
>                 // we should never reach this branch!
> ```

i think this is a mistake of copy paste? as in other branches of the match statement
___
*[`crates/evm/src/tests/test_precompiles/test_sha256.cairo` line 16 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5irJU2u94LBhXClU6:-Nm5irJU2u94LBhXClU7:b-6a4nns) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/evm/src/tests/test_precompiles/test_sha256.cairo#L16)):*
> ```Cairo
>     let mut vm = VMBuilderTrait::new_with_presets().build();
> 
>     let calldata = array![0xFF].span();
> ```

can we add an evm.codes link too? or a link to an only sha256 tool?
___
*[`crates/evm/src/tests/test_precompiles/test_sha256.cairo` line 37 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5itIQ-rIw22mG5ss0:-Nm5itIQ-rIw22mG5ss1:bvq16a6) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/evm/src/tests/test_precompiles/test_sha256.cairo#L37)):*
> ```Cairo
>     let mut vm = VMBuilderTrait::new_with_presets().build();
> 
>     vm.stack.push(0x20).unwrap(); // retSize
> ```

can we add an evm.codes link too?

**Review by bajpai244 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677)* status: 4 of 13 files reviewed, 6 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`crates/alexandria_math/src/sha256.cairo` line 277 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5iB-P2j0EaFhxcJkO:-Nm6EBjyAhuZrWUHq5Ks:b-ndmxj7) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/alexandria_math/src/sha256.cairo#L277)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

open question: should we add their tests as well? for soundness
this also applies to other packages we copy pasted i guess
</blockquote></details>

I also thought about this, but I think the code has already been tested for these tests, until unless we plan to change anything in the code we have copied from there, not sure adding the tests add anything much.
___
*[`crates/evm/src/precompiles/lib.cairo` line 27 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5iJV6CiAbMHpM1h80:-Nm6FJZM3Wu68PiRBKJA:b-x0vep) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/evm/src/precompiles/lib.cairo#L27)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

i think this is a mistake of copy paste? as in other branches of the match statement
</blockquote></details>

nice catch, removed.
___
*[`crates/evm/src/tests/test_precompiles/test_sha256.cairo` line 16 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5irJU2u94LBhXClU6:-Nm6FQPo2tEAZ5Iwzy2g:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/evm/src/tests/test_precompiles/test_sha256.cairo#L16)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

can we add an evm.codes link too? or a link to an only sha256 tool?
</blockquote></details>

done
___
*[`crates/evm/src/tests/test_precompiles/test_sha256.cairo` line 37 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5itIQ-rIw22mG5ss0:-Nm6FRCJ2S6pICmHGh9p:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/evm/src/tests/test_precompiles/test_sha256.cairo#L37)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

can we add an evm.codes link too?
</blockquote></details>

done

**Review by bajpai244 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677)* status: 4 of 13 files reviewed, 6 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`crates/alexandria_math/src/sha256.cairo` line 1 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5hxcpEIqdN53IRYW7:-Nm6G3iH6WQky9URi5-0:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/alexandria_math/src/sha256.cairo#L1)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

Lets add a comment at the top explaining that we copy pasted this alexandria code as a temporary solution to enable us to change scarb versions as we see fit, and add a link to alexandria
</blockquote></details>

done

**Review by bajpai244 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677)* status: 3 of 13 files reviewed, 6 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`crates/alexandria_math/src/sha256.cairo` line 72 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5ic2K8OGrvNjAct0E:-Nm6Gqpm18arCYQPy8GC:bfvrnd5) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/alexandria_math/src/sha256.cairo#L72)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

i see a lot of unwraps in their implementation, are they all safe unwraps?

i guess we'll see with some ef-tests if we get some panics,

but it'd be good to do some amount of sanity check that this code cannot panic, because we must not panic in the precompile
</blockquote></details>

I saw that as well, most of it seems to be to from a bigger type to a smaller one.

For now, I think we can take the implementation as it is, and rely on 2 security layers:
- ef-tests
- the code audit { if we end up using this, then this function will become part of our code's audit! }

Also, I think we can have an issue later on to dive deep into this implementation and see if the code can be made more safer, what do you think?

**Review by Eikix — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677)* status: 6 of 13 files reviewed, 3 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/alexandria_math/src/sha256.cairo` line 72 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5ic2K8OGrvNjAct0E:-Nm6P9se46s56_k84BWI:b5zk1ey) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/alexandria_math/src/sha256.cairo#L72)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

I saw that as well, most of it seems to be to from a bigger type to a smaller one.

For now, I think we can take the implementation as it is, and rely on 2 security layers:
- ef-tests
- the code audit { if we end up using this, then this function will become part of our code's audit! }

Also, I think we can have an issue later on to dive deep into this implementation and see if the code can be made more safer, what do you think?
</blockquote></details>

I think we should take some time to think of ways to break it and make it panic ourselves and not rely on audit as much as possible
Very often, we think that things can wait for later but it's generally not true and those things aren't done later on

We should go through the implementation now and add comment of type "safe unwrap because X" for each unwrap 
___
*[`crates/alexandria_math/src/sha256.cairo` line 1 at r3](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm6P3TbBsU4yDVj6OGK:-Nm6P3TbBsU4yDVj6OGL:b4igr74) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/98b65587b870fe60c22a298091ee4c65541d0c50/crates/alexandria_math/src/sha256.cairo#L1)):*
> ```Cairo
> // note: the code has been take from <https://github.com/keep-starknet-strange/alexandria/blob/main/src/math/src/sha256.cairo>
> ```

typo taken

**Review by bajpai244 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677)* status: 6 of 13 files reviewed, 3 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`crates/alexandria_math/src/sha256.cairo` line 72 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5ic2K8OGrvNjAct0E:-NmAaU8l9QOwH3vgfYtu:b-oxwa3b) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/alexandria_math/src/sha256.cairo#L72)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

I think we should take some time to think of ways to break it and make it panic ourselves and not rely on audit as much as possible
Very often, we think that things can wait for later but it's generally not true and those things aren't done later on

We should go through the implementation now and add comment of type "safe unwrap because X" for each unwrap
</blockquote></details>

@Eikix safety comments for unwraps have been added, as of now looks like they are safe unwraps! Feel free to check the comments, and lemme know if they look convincing to you as well :)

**Review by Eikix — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677)* status: 6 of 13 files reviewed, 2 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/alexandria_math/src/sha256.cairo` line 72 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm5ic2K8OGrvNjAct0E:-NmAcAEZ7pRjt4Lky2uf:b-ey36v8) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/083f06fbd04c6a474e2cc1198ec7f89ccab89af7/crates/alexandria_math/src/sha256.cairo#L72)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

@Eikix safety comments for unwraps have been added, as of now looks like they are safe unwraps! Feel free to check the comments, and lemme know if they look convincing to you as well :)
</blockquote></details>

great job!
___
*[`crates/alexandria_math/src/sha256.cairo` line 1 at r3](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm6P3TbBsU4yDVj6OGK:-NmAc84y6FZ1m-qDXxOP:bh20ps1) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/98b65587b870fe60c22a298091ee4c65541d0c50/crates/alexandria_math/src/sha256.cairo#L1)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

typo taken
</blockquote></details>

nit last comment

**Review by bajpai244 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677)* status: 6 of 13 files reviewed, 2 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`crates/alexandria_math/src/sha256.cairo` line 1 at r3](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-Nm6P3TbBsU4yDVj6OGK:-NmB0YZq8nat5MsoGWUR:b-qsseby) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/98b65587b870fe60c22a298091ee4c65541d0c50/crates/alexandria_math/src/sha256.cairo#L1)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

nit last comment
</blockquote></details>

fixed!

**Review by Eikix — APPROVED** [review]
lgtm 👑👑 congratulations

**Review by Eikix — APPROVED** [review]
lgtm

**Review by Eikix — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r2, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/677#-:-NmBKyEf6zR2TLoduP0q:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ClementWalter)

**Pull request merged**
