### PR TITLE
feat: implement 0x51 - MLOAD Opcode

### PR DESCRIPTION
**Pull request by khaeljy**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #242 Resolves: #245 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by khaeljy** [comment]
Awaiting resolution of #283

**Comment by danilowhk** [comment]
Hey @khaeljy #283 have been resolved and merged, could you resolve conflicts and check again? :)

**Comment by khaeljy** [comment]
> Hey @khaeljy #283 have been resolved and merged, could you resolve conflicts and check again? :)

Done!

**Review by enitrat — APPROVED** [review]
🔥

**Pull request merged**
