### PR TITLE
feat: ecAdd / ecMul

### PR DESCRIPTION
**Pull request by obatirou**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #856

## What is the new behavior?

Wrap ecAdd / ecMul

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/880)

### CODE REVIEW

**Comment by obatirou** [comment]
blocked by https://github.com/foundry-rs/starknet-foundry/issues/2397

**Comment by feltroidprime** [comment]
Some note : if ec_add or ec_mul returns None, it shouldn't be interpreted as (0,0) which a valid way of encoding the point at inifinity. It should be a precompile error

**Comment by obatirou** [comment]
> Some note : if ec_add or ec_mul returns None, it shouldn't be interpreted as (0,0) which is a valid way of encoding the point at inifinity. It should be a precompile error
> 
> See https://www.evm.codes/precompiled ` If the input is not valid, all gas provided is consumed and there is no return data, indicating a precompile contract error. Also, if not enough gas was given, there is no return data.`
> 
> The Option::None case is reflecting the input is not valid .

Thank you for spotting this !
Will make sure to take this into account when working on it again.
This draft PR is not ready as it does not compile due to the blocking issue.

**Comment by enitrat** [comment]
@obatirou https://github.com/foundry-rs/starknet-foundry/releases/tag/v0.30.0

**Pull request merged**
