### PR TITLE
FEAT : make chain_id an environmental variable

### PR DESCRIPTION
**Pull request by TAdev0**
Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Resolves: #641 

## What is the new behavior?

After this PR is merged : 
-  `chain_id` opcode grabs `chain_id` value from vm environment 
- When deployed , EOAs grab `chain_id` from `get_execution_info_syscall` call
- kakarot transaction execution uses `get_execution_info_syscall` to define `chain_id` value in the `env` environment variable

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/649)

### CODE REVIEW

**Comment by enitrat** [comment]
@greged93 can you confirm this is not an issue for EF-Tests?

**Comment by TAdev0** [comment]
I still need to figure out what the issue is with 3 tests not passing anymore.

**Comment by enitrat** [comment]
@TAdev0 use `set_chain_id` and set it to what it previously was in the tests with the signatures. That will make it compatible with what we had previously

**Comment by TAdev0** [comment]
@enitrat  i tried to do it (see last commit) but tests still fail. i guess i'm doing something wrong

**Comment by TAdev0** [comment]
Thank you, now tests pass !

**Comment by greged93** [comment]
I think it should be ok @enitrat

**Review by enitrat — APPROVED** [review]

**Pull request merged**
