### PR TITLE
Feat/integrate modexp precompile

### PR DESCRIPTION
**Pull request by bajpai244**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #699 

## What is the new behavior?

Integrates Modexp precompile.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727)

### CODE REVIEW

**Review by enitrat — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727)* status: all files reviewed, 3 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/evm/src/precompiles/modexp.cairo` line 133 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727#-Nq1Zm1mBYRBaThcd_s1:-Nq1Zm1mBYRBaThcd_s2:bij00mm) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/e070ff3753781a7e933bd34786f4f929ec8f006c/crates/evm/src/precompiles/modexp.cairo#L133)):*
> ```Cairo
> 
> fn calculate_iteration_count(exp_length: u64, exp_highp: u256) -> u64 {
>     let mut iteration_count: u64 = if exp_length <= 32 && exp_highp == 0 {
> ```

saves an equality check

actually this should be optimized by the compiler, would be nice if it was done automatically :thinking: 



_Suggestion:_
```Cairo
exp_length <= 33
```
___
*[`crates/evm/src/precompiles/modexp.cairo` line 135 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727#-Nq1Zb1I-Gki-m3z5VrP:-Nq1Zb1I-Gki-m3z5VrQ:undefined) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/e070ff3753781a7e933bd34786f4f929ec8f006c/crates/evm/src/precompiles/modexp.cairo#L135)):*
> ```Cairo
>     let mut iteration_count: u64 = if exp_length <= 32 && exp_highp == 0 {
>         0
>     } else {
> ```





_Suggestion:_
```Cairo
else if exp_length <= 32 {
            (exp_highp.bit_len() - 1).into()
} else { 
 ...
```
___
*[`crates/evm/src/precompiles/modexp.cairo` line 136 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727#-Nq1Zguf98wZcB86IQfo:-Nq1Zguf98wZcB86IQfp:b-j8wlx6) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/e070ff3753781a7e933bd34786f4f929ec8f006c/crates/evm/src/precompiles/modexp.cairo#L136)):*
> ```Cairo
>         0
>     } else {
>         if exp_length <= 32 {
> ```

saves an equality check



_Suggestion:_
```Cairo
< 33
```

**Review by bajpai244 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727)* status: all files reviewed, 3 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/evm/src/precompiles/modexp.cairo` line 133 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727#-Nq1Zm1mBYRBaThcd_s1:-Nq1aqFN-e6x1lUInn4o:b4t4g9b) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/e070ff3753781a7e933bd34786f4f929ec8f006c/crates/evm/src/precompiles/modexp.cairo#L133)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

saves an equality check

actually this should be optimized by the compiler, would be nice if it was done automatically :thinking:
</blockquote></details>

I guess u mean < 33
___
*[`crates/evm/src/precompiles/modexp.cairo` line 135 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727#-Nq1Zb1I-Gki-m3z5VrP:-Nq1bA5S65xrb48riyO7:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/e070ff3753781a7e933bd34786f4f929ec8f006c/crates/evm/src/precompiles/modexp.cairo#L135)):*
> ```Cairo
>     let mut iteration_count: u64 = if exp_length <= 32 && exp_highp == 0 {
>         0
>     } else {
> ```

done
___
*[`crates/evm/src/precompiles/modexp.cairo` line 136 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727#-Nq1Zguf98wZcB86IQfo:-Nq1bAuY4Iks0CEUowt1:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/e070ff3753781a7e933bd34786f4f929ec8f006c/crates/evm/src/precompiles/modexp.cairo#L136)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

saves an equality check
</blockquote></details>

done

**Review by enitrat — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727)* status: all files reviewed, 1 unresolved discussion (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/evm/src/precompiles/modexp.cairo` line 133 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727#-Nq1Zm1mBYRBaThcd_s1:-Nq1deiB4cSZ9yrvCEOB:bb7s9mg) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/e070ff3753781a7e933bd34786f4f929ec8f006c/crates/evm/src/precompiles/modexp.cairo#L133)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

I guess u mean < 33
</blockquote></details>

yeah

**Review by enitrat — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727)* status: all files reviewed, 1 unresolved discussion (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/evm/src/precompiles/modexp.cairo` line 133 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727#-Nq1Zm1mBYRBaThcd_s1:-Nq2WnA12XJfZzYMuxyj:b-mos2ls) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/e070ff3753781a7e933bd34786f4f929ec8f006c/crates/evm/src/precompiles/modexp.cairo#L133)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

yeah
</blockquote></details>

still needs change

**Review by bajpai244 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727)* status: all files reviewed, 1 unresolved discussion (waiting on @ClementWalter and @enitrat)

___
*[`crates/evm/src/precompiles/modexp.cairo` line 133 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727#-Nq1Zm1mBYRBaThcd_s1:-Nq2tNcME0WrfRdmpLJ3:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/e070ff3753781a7e933bd34786f4f929ec8f006c/crates/evm/src/precompiles/modexp.cairo#L133)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

still needs change
</blockquote></details>

done

**Review by enitrat — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/727)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ClementWalter)

**Pull request merged**
